config/routes.rb
Rails.application.routes.draw do

  root 'links#index'

  resources :links, except: :index do
    resources :comments, only: [:create, :edit, :update, :destroy]
  end

   get '/comments' => 'comments#index'

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end

  resources :users, only: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :link

  validates :body, presence: true

end

app/models/link.rb
class Link < ApplicationRecord
  has_many :comments
  belongs_to :user

  validates :title,
	     presence: true,
	     uniqueness: { case_sensitive: false }

  validates :url,
	     format: { with: %r{\Ahttps?://} },
             allow_blank: true


end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :links, dependent: :destroy
  has_many :comments

  validates :username,
	     presence: true,
	     length: { minimum: 3  },
	     uniqueness: { case_sensitive: false }

  validates :password, length: { minimum: 8 }

  def owns_link?(link)
    self == link.user
  end

  def owns_comment?(comment)
    self == comment.user
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def login(user)
    session[:user_id] = user.id	  
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logout
    session.delete(:user_id)
    @current_user = nil 
  end

  def logged_in?
    current_user.nil? ? false :true	  
  end

  def prevent_unauthorized_user_access
    redirect_to root_path, notice: 'sorry, you cannot access that page', status: :found unless logged_in?
  end

  def prevent_logged_in_user_access 
    redirect_to root_path, notice: 'sorry, you cannot access that page', status: :found if logged_in?
  end

  helper_method :current_user, :logged_in?
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :prevent_unauthorized_user_access, except: :index
  before_action :set_variables, only: [:edit, :update, :destroy]
  def index
  end

  def edit
  end

def create
  @link = Link.find_by(id: params[:link_id])
  @comment = @link.comments.new(user: current_user, body: comment_params[:body])

  if @comment.save
    redirect_to @link, notice: 'Comment created'
  else
    redirect_to @link, notice: 'Comment was not saved. Ensure you have entered a comment'
  end
end

private

def comment_params
  params.require(:comment).permit(:body)
end 

def set_variables
  @link = Link.find_by(id: params[:link_id])
  @comment = @link.comments.find_by(id: params[:id])
end


end

app/controllers/links_controller.rb
class LinksController < ApplicationController
before_action :prevent_unauthorized_user_access, only: [:new, :edit]

  def index
    @links = Link.all
  end

  def new
    @link = Link.new
  end

  def create
    @link = current_user.links.new(link_params)

    if @link.save
      redirect_to root_path, notice: 'Link sucessfully created'
    else
      render :new
    end
  end

  def show
    @link = Link.find_by(id: params[:id])
    @comments = @link.comments
  end

  def edit
    link = Link.find_by(id: params[:id])

    if current_user.owns_link?(link)
      @link = link
    else
      redirect_to root_path, notice: 'Not authorized to edit this link'
    end
  end


  def destroy
   link = Link.find_by(id: params[:id])

    if current_user.owns_link?(link)
      link.destroy
      redirect_to root_path, notice: 'Link successfully deleted'
    else
      redirect_to root_path, notice: 'Not authorized to delete this link'
    end
  end

  def update
    @link = current_user.links.find_by(id: params[:id])

    if @link.update(link_params)
      redirect_to root_path, notice: 'Link successfully updated'
    else
      render :edit
    end
  end


  private

  def link_params
    params.require(:link).permit(:title, :url, :description)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :prevent_logged_in_user_access, except: :destroy
  before_action :prevent_unauthorized_user_access, only: :destroy


  def new
  end

  def create
    user = User.find_by(username: login_params[:username])

    if user && user.authenticate(login_params[:password])
      login(user)
      redirect_to root_path, notice: 'Logged in' 
    else
      flash.now[:notice] = 'Invalid username / password combination'
      render :new
    end
  end

  def destroy
   logout
   redirect_to root_path, notice: 'Logged out'
  end


  private
  
  def login_params
    params.require(:session).permit(:username, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :prevent_logged_in_user_access
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      login(@user)
      redirect_to root_path, notice: 'Logged in'
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/edit.html.erb
<h1>Comments#edit</h1>
<p>Find me in app/views/comments/edit.html.erb</p>

app/views/comments/index.html.erb
<h1>Comments#index</h1>
<p>Find me in app/views/comments/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JumpNews</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <%= render 'shared/navbar' %>

  <body class="container">
    <main>
      <% if flash[:notice] %>
	<p class="alert alert-info">
	<%= flash[:notice] %>
	</p>
      <% end %>


    <%= yield %>
    </main>
  </body>
</html>

app/views/links/_form.html.erb
<%= form_for @link do |f| %>
  <%= render "shared/errors", object: @link %>

  <div class="form-group">
    <%= f.text_field :title, required: true, class: "form-control", placeholder: "title" %>
  </div>

  <div class="form-group">
    <%= f.url_field :url, class: "form-control", placeholder: "url" %>
  </div>

  <div class="form-group">
    <%= f.text_area :description, class: "form-control", placeholder: "description", rows: 15 %>
  </div>

  <div class="form-group">
    <%= f.button :submit, class: "btn btn-success" %>
  </div>
<% end %>

app/views/links/edit.html.erb
<section class="edit-link">
  <header>
    <h1>
      Edit link
    </h1>
  </header>

  <div class="row">
    <div class="col-sm-6">
      <%= render 'form' %>
    </div>
  </div>
</section>

app/views/links/index.html.erb
<section class="all-links">
  <% @links.each do |link|  %>
    <div class="link">
      <div class="title">
        <%= link_to link.title, (link.url? ? link.url : link) %>

        <% if link.url? %>
          <span>
            ( <%= link.url %> )
          </span>
        <% end %>
      </div>

      <div class="metadata">
	 <span class="time-created">

           <% if logged_in? && current_user.owns_link?(link) %>
             <span class="edit-link">
               <%= link_to "edit", edit_link_path(link) %>
             </span>

             <span class="delete-link">
               <%= link_to "delete", link, method: :delete, data: { confirm: "Are you sure?" } %>
             </span>
         <% end %>


          <%= time_ago_in_words(link.created_at) %> ago
        </span>
      </div>

    </div>
  <% end %>
</section>

app/views/links/new.html.erb
<section class="new-link">
  <header>
    <h1>
      submit a link
    </h1>
  </header>

  <div class="row">
    <div class="col-sm-6">
      <%= render 'form' %>
    </div>
  </div>
</section>

app/views/links/show.html.erb
  <% if logged_in? %>
    <div class="add-comment row">
      <div class="col-sm-6">
        <%= form_for :comment, url: link_comments_path(@link) do |f| %>
          <div class="form-group">
            <%= f.text_area :body, class: "form-control", placeholder: "The quick brown fox...", rows: 10, required: true %>
          </div>

          <div class="form-group">
            <%= f.button "add comment", class: "btn btn-success" %>
          </div>
      <% end %>

<div class="all-comments row">
    <div class="col-sm-12">
      <% if @comments.present? %>
        <h3>
            Comments
        </h3>
      <% end %>
      
      <% @comments.each do |comment| %>
        <div class="comment">
          <p class="comment-owner">
            <strong>
              <%= comment.user.username %>
            </strong>

            <span class="comment-created small">
              <%= time_ago_in_words(comment.created_at) %> ago
            </span>
          </p>

          <p>
            <%= comment.body %>
          </p>
        </div>
      <% end %>
    </div>
  </div>


      </div>
    </div>
  <% end %>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <ul class="errors aleart alert-danger">
    <% object.errors.full_messages.each do |msg| %>
      <li> <%= msg %>  </li>
    <% end %>
  </ul>
<% end  %>

app/views/shared/_navbar.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-light" style="background-color: orange">
    <%= link_to "jump news", root_path, class: "navbar-brand" %>
    <ul class="nav navbar-nav">
      <li><%= link_to "new", "#", class: "nav-item nav-link active" %></li>
      <li><%= link_to "comments", comments_path, class: "nav-item nav-link active" %></li>
 
      <% unless logged_in? %>
	<li><%= link_to "signup", new_user_path, class: "nav-item nav-link active" %></li>
	<li> <%= link_to "login", new_session_path, class: "nav-item nav-link active" %></li>
       <% end %>

       <% if logged_in? %>
	<li><%= link_to "submit a link", new_link_path , class: "nav-item nav-link active" %></li>
	 <li><%= link_to "logout", sessions_path, method: :delete, class: "nav-item nav-link active" %></li>
      <% end %>
   </ul>
  </nav>
</header>

app/views/users/new.html.erb
<section class="register-user">
  <header>
    <h1>
      Create a new Account
    </h1>
	
    <div class="row">
      <div class="col-sm-6">
        <%= form_for @user do |f| %>
	<%= render "shared/errors", object: @user %>
	<div class="form-group">
	  <%= f.text_field :username, class: "form-control", required: true, minlength: 3, placeholder: "username"  %>
	</div>

	<div class="form-group">
	  <%= f.password_field :password, class: "form-control", required: true, minlength: 8, placeholder: "password"  %>
	</div>

	<div class="form-group">
 	  <%= f.button "Register", class: "btn btn-primary"  %>
	</div>


        <% end %>
      </div>
    </div>
  </header>
</section>